# Whether messages should be send to console.
Send-Message-To-Console: true
# If enabled, messages will only be sent within Range
# blocks of the player that got the advancement
Radius:
  Enabled: false
  Range: 100.0