name: CAM
main: net.insprill.cam.CAM
version: 1.0.1.0
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  cam:
    aliases: [ customadvancementmessages ]
    permission: cam.use
    description: Base CAM command.

permissions:
  cam.*:
    description: Gives access to all CAM commands
    children:
      cam.command.help: true
      cam.command.version: true
      cam.command.debug: true
      cam.command.revoke: true
      cam.command.reload: true
  cam.command.*:
    description: Gives access to all CAM commands
    children:
      cam.command.help: true
      cam.command.version: true
      cam.command.debug: true
      cam.command.revoke: true
      cam.command.reload: true
  cam.command.help:
    description: Gives access to "/cam help"
  cam.command.version:
    description: Gives access to "/cam version"
  cam.command.debug:
    description: Gives access to "/cam debug"
  cam.command.revoke:
    description: Gives access to "/cam revoke"
  cam.command.reload:
    description: Gives access to "/cam reload"